//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int bookid { get; set; }
        public string bookname { get; set; }
        public string ISBN { get; set; }
        public Nullable<decimal> price { get; set; }
        public string bookcategory { get; set; }
    }
}
