//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kişiler
    {
        public int kisiid { get; set; }
        public string kisiisim { get; set; }
        public string kisisoyisim { get; set; }
    }
}
